### ISSUE TITLE
bunun adı nedir?

### ISSUE THREAD

**Issue by hasanalizxc** [cihanmehmet/cloudflarebypass#1]
Merhaba hocam. bu yapılan şeklin genel bir adı vardır elbet nedir?

██████╗ ███╗   ██╗███████╗██████╗ ███████╗███████╗ ██████╗ ██╗    ██╗   ██╗███████╗██████╗ 
██╔══██╗████╗  ██║██╔════╝██╔══██╗██╔════╝██╔════╝██╔═══██╗██║    ██║   ██║██╔════╝██╔══██╗
██║  ██║██╔██╗ ██║███████╗██████╔╝█████╗  ███████╗██║   ██║██║    ██║   ██║█████╗  ██████╔╝
██║  ██║██║╚██╗██║╚════██║██╔══██╗██╔══╝  ╚════██║██║   ██║██║    ╚██╗ ██╔╝██╔══╝  ██╔══██╗
██████╔╝██║ ╚████║███████║██║  ██║███████╗███████║╚██████╔╝███████╗╚████╔╝ ███████╗██║  ██║
╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚══════╝ ╚═══╝  ╚══════╝╚═╝  ╚═╝

**Comment by cihanmehmet** [comment]
Aşağıdaki linkteki siteyi bir incele işine yarayacağını düşünüyorum
http://patorjk.com/software/taag/#p=display&f=Big&t=CMD
